# Generated by Django 2.2.24 on 2025-05-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20250531_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(blank=True, choices=[(None, 'Не указано'), (True, 'Да'), (False, 'Нет')], null=True, verbose_name='Новостройка'),
        ),
    ]
