# Generated by Django 2.2.24 on 2025-06-01 01:10

import phonenumbers
from django.db import migrations


def standardized_phone_number(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')

    for flat in Flat.objects.all():
        phone_number = flat.owners_phonenumber
        if phone_number:
            parse_phone_number = phonenumbers.parse(phone_number, 'RU')
            if phonenumbers.is_valid_number(parse_phone_number):
                standardized_phone_number = phonenumbers.format_number(
                    parse_phone_number,
                    phonenumbers.PhoneNumberFormat.E164)

                flat.owner_pure_phone = standardized_phone_number
            else:
                flat.owner_pure_phone = None
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(standardized_phone_number)
    ]
